spring:
  web:
    resources:
      static-locations: classpath:data/, classpath:entity/, classpath:ui/, classpath:static/
  jackson:
    serialization:
      fail-on-empty-beans: false
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    static-path-pattern: /game-data/**
  main:
    web-environment: false
    allow-bean-definition-overriding: true
server:
  error:
    include-stacktrace: never
  tomcat:
    relaxed-query-chars: ['{','}','[',']','\','/']
    relaxed-path-chars: ['{','}','[',']','\','/']
  port: 8085
  servlet:
    context-path: /
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %-5level- %msg%n'
  level:
    root: INFO
    '[org.springframework.beans]': WARN
springfox:
  documentation:
    enabled: true
    
